### ISSUE TITLE
Add area scaling for pixel sprites as well as scaling options in char.ini

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#218]
Pixelated sprites look horrible when scaled not according to multiples of 2, such as 256x192 looking horrible in all resolutions leading up to 512x384 and beyond until 1024x768.
Open Broadcaster Software has introduced Area Scaling for pixel art:
https://obsproject.com/forum/threads/new-scale-filtering-mode-area-averaging.77590/
https://github.com/obsproject/obs-studio/pull/1715

I tested it with my recording setup and it works extremely well with pixel art.
More info on the algorithm:
https://entropymine.com/imageworsener/pixelmixing/

As far as char.ini options go, it should have "scaling=" in [Options], and [Scaling] to define scaling algorithms per-emote name for more fine-tuning (due to CG's etc.)

**Comment by oldmud0** [comment]
code where
all i see are shaders

**Comment by oldmud0** [comment]
Area scaling isn't the same thing as nearest-neighbor scaling though. There's a significant difference between the two.

**Comment by in1tiate** [comment]
unepic of you to comment this

**Comment by in1tiate** [comment]
Frankly, I don't see this being viable. The way scaling is currently done is via Qt's inbuilt `Qt::TransformationMode`s, of which there are two: `Qt::SmoothTransformation` and `Qt::FastTransformation`. Unless there's a way to add more modes, I would rather not write large swaths of image resizing code so that pixel art looks slightly better.

**Comment by oldmud0** [comment]
After examination, area scaling is still somewhat blurry and does not yield enough of a return to justify its development time.
