### ISSUE TITLE
Neither bass nor Discord-rpc is included in the Linux release on the homepage

### ISSUE THREAD

**Issue by Cerapter** [AttorneyOnline/AO2-Client#240]
why

**Comment by gameboyprinter** [comment]
the linux builds are linked differently iirc

**Comment by oldmud0** [comment]
Sorry for the nonresponse. I have been aware of this issue since release time, but there were other problems with the Linux release that prompted me to focus on fixing the CI instead of fixing it manually. Moreover, it had been fixed on the standalone package for some time now. Anyway, I fixed it now.
