### ISSUE TITLE
Mismatched case between filename and char.ini doesn't load file on macOS/Linux, but works on Windows

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#264]

**Comment by scatterflower** [comment]
this has been a problem since linux builds first came out. there was a change that made all paths used lowercase, but on linux, each path also needs to be made lowercase. its a nasty hack, but i dont know of any better way, short of recursively checking each path for case insensitive inequality, which is horribly slow.
personally, i vote for a wontfix on this one, unless i misunderstood the issue.

**Comment by oldmud0** [comment]
The [case-sensitive FS compile flag](https://github.com/AttorneyOnline/AO2-Client/blob/ec1c95bdb33dd063880c4cb6c3c9c3cf5d0ed454/src/path_functions.cpp#L18) should have been enabled - was it not?

**Comment by in1tiate** [comment]
@raidensnake

**Comment by raidensnake** [comment]
apfs as default.

**Comment by scatterflower** [comment]
apfs is by default case insensitive

**Comment by Crystalwarrior** [comment]
Mac no longer supported, reopen if still present on linux builds
