### ISSUE TITLE
[2.8.5] Evidence shown twice during preanimation with no interrupt.

### ISSUE THREAD

**Issue by raidensnake** [AttorneyOnline/AO2-Client#272]
For some reason when you show a piece of evidence it plays it twice during a pre-animation with no interrupt on. It doesn't do it at any other time.

**Comment by raidensnake** [comment]
Demonstration:
![2020-09-01 11-20-07](https://user-images.githubusercontent.com/1094029/91838417-5ddec300-ec45-11ea-89ce-393a3f67521a.gif)

**Comment by raidensnake** [comment]
@scatterflower any ideas?

**Comment by scatterflower** [comment]
i'll look into this after work

**Comment by raidensnake** [comment]
any updates in this issue?

**Comment by in1tiate** [comment]
Caused by `handle_chatmessage_3` being called twice in the case of a non-interrupting preanimation - not a problem in and of itself, but it results in the evidence presenting function being called twice as well. Introducing a variable to track whether the current message has already presented evidence has proven effective.
