### ISSUE TITLE
The ? (Help) button on the settings and casing pop-ups seem to do nothing.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#295]
For someone looking for actual help they'd be better off using tooltips. Not sure if this is something that can be helped but it can be confusing for people who don't know to just hover over stuff for explanations. Pictured here: [Link](https://i.imgur.com/kagYeVq.png)

**Comment by in1tiate** [comment]
This button does nothing because it is not created or controlled by us - it's a Windows feature known as a [HelpButton](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.helpbutton?view=netcore-3.1). For some ungodly reason, Qt adds the flag for this to dialogs by default. It's known as `Qt::WindowContextHelpButtonHint` - should be an easy fix, for anyone who feels like tackling it.
