### ISSUE TITLE
[2.8.6 Suggestion] Enable Dual Stacking support for both IPv4 and IPv6 to futureproof AO.

### ISSUE THREAD

**Issue by raidensnake** [AttorneyOnline/AO2-Client#318]
Due to some recent requests it would be an idea to support IPv6 as well as IPv4 for the client, server and master server. Some users have reported being unable to connect to AO due to their ISP not supporting NAT64 on their networks. Also it would be good to include a way of being able to connect using either both IP's or use a dns resolution option depending on if the client is using IPv4 only, IPv6 only or has both.

**Comment by oldmud0** [comment]
Lack of NAT64 connectivity has a severe effect on overall Internet experience. I'm not sure how your users can tolerate being effectively cut off from the IPv4 Internet.

Client:

 - Public list - should be OK to parse v6 addresses.
 - Favorites list - favorites list uses colons as delimiters, so only hostnames/FQDNs can be used to represent v6 servers.

Server:

 - Listening - should be OK to listen to v6 sockets. Those should be `AF_INET6` sockets by default.
 - Advertising - not really much can be done here other than to send a hostname. If that is done, however, it's probably better to use a redesigned heartbeat packet instead of continuing to overload the heartbeat packet with optional parameters.

Master server:

 - Database - should be OK to store v6 addresses. But might need to add a hostname column to allow servers to offer both v4 and v6 addresses based on the A/AAAA records of that name.
 - Connector - should be OK to accept v6 connections.
 - Kernel:
  - Need to parse optional hostname parameter.
  - Need to validate that the hostname resolves to the advertiser's address.

**Comment by raidensnake** [comment]
as it stands through trial and error I've been unable to get the client to read Ipv6 addresses cause of the way the network manager is designed.

**Comment by oldmud0** [comment]
Please elaborate.

**Comment by raidensnake** [comment]
I've tried a couple of things that scatterflower suggested like changing the seperator in the favourited and changing the code to invoke QHostAddress however nothing worked. It can't even resolve a hostname not even a valid Ipv6 address without saying it's offline of completely crashing for no reason.

**Comment by raidensnake** [comment]
nvm I found out the reason why with the help of @scatterflower it was due to tsuserver not supporting Ipv6. I created a draft PR so support can be added. https://github.com/AttorneyOnline/AO2-Client/pull/321
