### ISSUE TITLE
"Preanim" checkbox causes realization sound to be cut off when used on an emote with no preanim or sound effect

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#344]
Steps to reproduce:

Pick Phoenix or something. Use an emote with no preanim or sound effect.
Check the preanim tickbox, and press the realization button.
Send a message. The realization sound will be cut off near-instantly.

**Comment by collinxchu** [comment]
This is extremely old behavior. We used to hypothesize that because the "realization" plays after preanims, it gets interrupted immediately after by the sound engine initializing whatever sound is in the [soundN] category on whatever timer has been given. I believe a [soundT] of 0 used to cuck the sound entirely.

**Comment by in1tiate** [comment]
Indirectly fixed by #355.
