### ISSUE TITLE
Interface not updating on position/character switch

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#47]
This sounds like a server-side regression (since I was able to reproduce on 2.4.10?), but I will report it here anyway. For instance, when switching to `jud`, the judge controls are not displayed as they should be.

**Comment by Cerapter** [comment]
Can partially replicate the issue, though it is definitely not server-side (since the judge controls are client-side only).

If the user types `/pos jud` (or anything that begins with that -- `/pos juddddddd` is also valid, it gives the user fully functional judge buttons, but keeps the user in their current pos, because tsuserver checks for EXACTLY `/pos jud` before switching the user's position), then the judge buttons are granted. Similarly, if the users `/pos`-es away from the judge position, the judge buttons are removed.
This is due to [this piece of code in `courtroom.cpp`](https://github.com/AttorneyOnline/AO2-Client/blob/50af363b735399876fbdd3635e517e83c8dab946/courtroom.cpp#L2622) -- the tsuserver commands are baked into the client itself.

However, the position dropdown doesn't have such code that grants the judge-specific buttons, [as you can see](https://github.com/AttorneyOnline/AO2-Client/blob/50af363b735399876fbdd3635e517e83c8dab946/courtroom.cpp#L2887).

The fix is relatively simple: hide away the judge buttons every time, and in the fourth case of the `p_index` switch, make them show.

**Comment by oldmud0** [comment]
Closed by #48
