### ISSUE TITLE
Disconnecting audio device and plugging back in results in no sound. 

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#561]
I run my sound through a secondary monitor - but when that monitor goes to sleep, upon turning it back on, my AO sound will be completely muted. I presume this is the case for any other audio device but do not have another handy to test.

Can be somewhat worked around by changing the audio device back and forth in the settings and then reloading theme. Reloading theme on its own is not sufficient, however.

**Comment by in1tiate** [comment]
This is caused by a disparity in the functionality of `initBASS()` and `doBASSReset()`. initBASS is only called on first start up, or when the options menu detects that the audio device has been changed. doBASSReset is called whenever the application notices that the device is no longer initialized, i.e. it has been disconnected. While initBASS properly checks for user settings when deciding what audio device to reinitialize, doBASSReset ignores user settings and initializes the system default audio device. In most circumstances, users are already using the default audio device, making this a non-issue.

To fix this, parity must be restored between initBASS and doBASSReset.

**Comment by in1tiate** [comment]
Or, because I'm not good at programming, I can just make the reload theme button call initBASS. That seems to work.
