### ISSUE TITLE
Remove demo playback

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#566]
Demo playback is barely functional, and in its current state is a hacked together reference implementation with large amounts of complexity added for very little practical gain. Additionally, the sole maintainer of demo playback has left the project and no developer I've talked to wants to work on it.

**Comment by likeawindrammer** [comment]
It's a good argument but the same could be said about most of the AO2 source code. Considering that I think the only sensible solution is either rewrite the client from scratch or not add buggy features added after Longbyte started his refactor just for the sake of feature parity.

**Comment by oldmud0** [comment]
Although the code lacks polishing, the feature is functional and is used by players to record cases to upload later; removing it would render it impossible to play back past sessions. Lack of maintenance is an endemic problem in the code base and is not specific to this feature. Please report bugs on the issue tracker if you find any, so that people who want to work on the project can see what parts are in need of attention.
