### ISSUE TITLE
iniswaps.ini not updated when adding an iniswap to dropdown

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#773]
**To reproduce**
1. Put name in iniswap dropdown
2. Switch chars
3. Iniswap dropdown resets

**Expected behavior**
Iniswaps.ini in main base/ folder is updated and saved

**Version:**
 - OS: Windows 10
 - Version or branch: ao2.10-alpha #788

**Comment by Salanto** [comment]
Not reproducible on master or 2.10-alpha using your reproduction steps.
The iniswaps file is updated accordingly in base and other chars have the characters you typed in are accessible when switching to another. As dumb as this behaviour is given character folders can have that file too.
Closing this issue until better steps are provided or an actual bug here is found.
