### ISSUE TITLE
 Regression: Custom chatboxes do not work 

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#78]
Supposedly, before 2.6, a custom chatbox could be placed in base/misc and be used to modify an individual character's chatbox, but the feature does not work since 2.6.

Apparently, custom chatbox support existed before 2.6, despite my understanding that it was added as part of the CC client. This issue will require some investigation.

(@oldmud0, https://gitlab.com/AttorneyOnline/AO2-Client/issues/78)

**Comment by stonedDiscord** [comment]
didn't this exist since 1.7.3
i think it was controlled using the char.ini file

**Comment by in1tiate** [comment]
To expand on what I mentioned on GitLab - Custom chatbox support has existed to my knowledge since 2.4 (and probably before), but implementation of this feature was changed in 2.6. Previous implementation required only the chatbox to be present under base/misc - this is no longer the case, as each chatbox must now have its own subfolder. These `misc` subfolders have eliminated the need to add shout bubble GIFs to each character folder - they can now be put in a misc subfolder and defined under `chat` and `shouts` in each character's `char.ini`.

Possible fix would be to check if a chatbox file exists under the name specified in the ini under base/misc before checking for a folder, and if found use it instead - though this is more of a simple change than a regression.
