### ISSUE TITLE
De-hardcode \f and \s

### ISSUE THREAD

**Issue by Yakkak** [AttorneyOnline/AO2-Client#794]
**Is your feature request related to a problem? Please describe.**
I would like to see `\f`, `\s` and possibly the future feature `\p` be able to be configurable and not hard-coded much like text color commands, as quite a few folks are not a fan of it's current command implementation. 

**Describe the solution you'd like**
I can see this either being done client side or server side, with the former listing out the option in some sort of .ini file in the "themes" folder, or server-side where the server recognizes a specific command/character as the means to play the effect. By default it can be `\f`, `\s` and possibly `\p` but regardless of implementation, the option to change it to something else would be great.

**Describe alternatives you've considered**
None that I can think up of.

EDIT: I did came up with something: Replacing `\f`, `\s` and `\p` with symbols instead, an example being off of the top of my head, the characters @, # and $. Could be different symbols, but the idea is that they're easily accessible characters that can be dropped into a sentence at a drop of a keystroke or two on one hand.

**Comment by oldmud0** [comment]
Technically this has now been burned into the protocol. There is no way to represent these effects other than these control sequences as they don't get translated into binary or anything like that, so there isn't an additional layer of abstraction we can fall back to.

If you really want, you can have the server replace some incoming character sequence of your choice with the canonical `\f`, `\s`, etc. which won't be visible to players.

**Comment by in1tiate** [comment]
Worth noting is that in the unreleased 2.7 client version, flashes and shakes were indeed controlled by symbols. This was changed deliberately so as not to conflict with inline colors, which *also* use symbols, as well as because the symbols used (and indeed, the exact same symbols you propose) were actually quite common in dialogue and would thus be inadvertently replaced during the course of normal conversation. There were a lot of accidental flashbangs when talking about cost, for example, or random earthquakes when the @ symbol was used as part of an email address or simply as a shortcut.

As oldmud0 remarks, you can do this server-side if you really want, but it is worth mentioning that we tried this and it didn't work out so well.
