### ISSUE TITLE
Android version can't find base folder 

### ISSUE THREAD

**Issue by EpicMario5345** [AttorneyOnline/AO2-Client#876]
Hello, fourth Android user here, and I have a problem regarding the base folder.
For some reason, the app cannot find it, and I tried almost everything to get it to work.
Am I doing something wrong?

**Comment by Satoru-1816** [comment]
The new way AO Android looks for the base folder is kinda unintuitive at first, yeah.
You can try this out, same solution I gave to someone else with the same issue: Just put the "base" folder in your internal storage. Keep in mind that it only works if it's named "base" like in this [screenshot](https://cdn.discordapp.com/attachments/278576491191599104/1029920906673401876/unknown.png) and not inside a folder named "AO", since that was changed some time ago.

**Comment by stonedDiscord** [comment]
![Screenshot_20221024-073331_My Files](https://user-images.githubusercontent.com/10584181/197455069-1483436a-0e40-46d8-b499-3ff478949a2e.jpg)
works on my machine ™️

**Comment by EpicMario5345** [comment]
Nope, still doesn't work. I renamed it and even redownloaded it, but it still says it can't find it.

**Comment by EpicMario5345** [comment]
Woops closed it accidentally

**Comment by stonedDiscord** [comment]
Did you put it on the SD card or the internal storage

**Comment by EpicMario5345** [comment]
Internal storage, download folder.

**Comment by EpicMario5345** [comment]
Btw here's what my base folder looks like
https://ibb.co/CVSd5m1

**Comment by EpicMario5345** [comment]
Update: I moved the 'base' follow to the '0' folder and it works now!
Thanks for the help!
