### ISSUE TITLE
Picking "spectator" on first join in 2.10.2 softlocks due to not loading theme

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#912]
**Describe the bug**
Picking "spectator" on first join in 2.10.1 soft-locks you due to the theme not being properly loaded, leaving you staring at a tiny box of just the IC log.

**To reproduce**
1. Join a server
2. In character select screen, click "Spectate"
3. The theme won't load and you'll be stuck staring at the IC log and nothing else

**Expected behavior**
The theme loads

**Screenshots**
(this is 2.10.2 Salanto just didn't update the window title/version number yet)

https://github.com/AttorneyOnline/AO2-Client/assets/3470436/654dedf2-3b79-4d66-a0fb-167cc0e4595b

**Version:**
 - OS: Windows 10
 - Version or branch: 2.10.2

**Comment by in1tiate** [comment]
2.10.2 is not presently an actual version, so I tested this on `master` as of commit https://github.com/AttorneyOnline/AO2-Client/commit/80939aa09228d76267a9efd2893cc5c961890cda and was unable to reproduce. Please confirm that the issue is still present either in a release version or current `master`.

**Comment by Salanto** [comment]
2.10.2 is no longer being developed with the new charselect code as it contains a bunch of other changes to the UI system. As such this issue is no longer valid/relevant.
